финальный проект спринта 9 готов
ChertkovFedor/java-filmorate pull request #1
Opened 2022-11-23 01:18 UTC by ChertkovFedor

2022-11-24 14:43 UTC, db-exp requested changes

2022-11-24 14:43 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
В Java классы имеются в CamelCase

2022-11-24 14:43 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    FilmController filmController;
не хватает модификатора доступа, лучше сразу делать private final

2022-11-24 14:43 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    UserController userController;
не хватает модификатора доступа, лучше сразу делать private final

2022-11-24 14:43 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private List<Film> films = new ArrayList<>();
тут лучше  Map, тогда в find все будет просто по индексу

2022-11-24 14:43 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private List<User> users = new ArrayList<>();
лучше Map

2022-11-24 14:43 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
Давай добавим тесты на ValidationException

2022-11-24 23:02 UTC, ChertkovFedor commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
Опечатка, поправлю

2022-11-24 23:04 UTC, ChertkovFedor commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    FilmController filmController;
Если делать final, то не получается сделать @BeforeEach. Просит конструктор. Если указать только приватное использование, этого достаточно?

2022-11-24 23:04 UTC, ChertkovFedor commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    UserController userController;
Если делать final, то не получается сделать @BeforeEach. Просит конструктор. Если указать только приватное использование, этого достаточно?

2022-11-24 23:09 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private List<Film> films = new ArrayList<>();
Да, изначально и была взята Map. Но с Map ни в какую не проходят тесты Postman. Показывает ошибки. Хотя, если делать запросы в ручную с теми данными, что передает во время тестов Postman, то все работает корректно.
В связи с этим структура была поменяна на List, тесты все стали корректными.
Нужно прислать скрины не пройденных тестов? Как решить проблему?

2022-11-24 23:09 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private List<User> users = new ArrayList<>();
Аналогично films

2022-11-24 23:12 UTC, ChertkovFedor commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
Так там же отдельный класс validationTest. Он тестирует всю валидацию выдающую ValidationException. 
Ты имеешь в виду что-то другое?

2022-11-26 22:45 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    FilmController filmController;
да

2022-11-26 22:45 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +    UserController userController;
да

2022-11-26 22:53 UTC, db-exp requested changes
Пару небольших моментов поправить

2022-11-26 22:53 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Integer newId = 1;
private?

2022-11-26 22:53 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    int newId = 1;
private?

2022-11-26 22:53 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
Я бы добавил еще проверку, когда null передают в тесты
Не обязательно

2022-11-26 22:53 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private List<Film> films = new ArrayList<>();
Внутри можно Map, а наружу отдавать List как и сейчас - это сильно сократило бы количество кода

2022-11-26 22:53 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private List<Film> films = new ArrayList<>();
По желанию

2022-11-27 13:46 UTC, ChertkovFedor commented on src/test/java/ru/yandex/practicum/filmorate/controllerTest.java
> +public class controllerTest {
> Я бы добавил еще проверку, когда null передают в тесты Не обязательно

Если ты имеешь в виду проверку когда в виде user или film передается null, то у меня эта проверка зашита в валидации (ValidationTest).

2022-11-27 14:48 UTC, db-exp approved these changes

2022-11-28 21:19 UTC, merged