Подключена база данных
ChertkovFedor/java-filmorate pull request #3
Opened 2023-01-30 22:01 UTC by ChertkovFedor

![image_2023-01-31_00-54-13](https://user-images.githubusercontent.com/105892758/215604845-21654967-1533-41c3-b2ed-8b0b9a3cb6b2.png)

2023-02-06 22:18 UTC, noittom-yandex-team-ru commented
looks good, just check build failures

2023-02-24 21:01 UTC, db-exp requested changes

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +        jdbcTemplate.update(sql, id);
лучше проверять что возвращает update, тогда точно будет понятно удалено или нет

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +            jdbcTemplate.update(sql, filmId, userId, filmId);
лучше проверять что возвращает update, тогда точно будет понятно удалено или нет

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +            jdbcTemplate.update(sql, filmId, userId, filmId);
лучше проверять что возвращает update

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +    public Film update(Long id, Film film) {
"Можно лучше" - когда в рамках одного метода делают несколько изменений в БД нужно оборачивать в Transational, чтобы не получилось неконсистентности данных

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorageImpl.java
> +        jdbcTemplate.update(sql, user.getEmail(), user.getLogin(),
так же как и для film

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorageImpl.java
> +        jdbcTemplate.update(sql, id);
так же как и для film

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorageImpl.java
> +    public void deleteFriend(Long id, Long idFriend) {
так же как и для film - update лучше проверять

2023-02-24 21:01 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorageImpl.java
> +        String sql = "SELECT USER_ID, EMAIL, LOGIN, USER_NAME, BIRTHDAY " +
лучше в длинных запросах с большим количеством таблиц использовать еще и псевдонимы
например, from users u1

2023-02-25 20:25 UTC, db-exp approved these changes

2023-02-27 16:42 UTC, merged